name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'
        required: true
        default: '1'
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'x.xx.x'
      nextVersion:
        description: 'Next version'
        required: true
        default: 'x.xx.x-SNAPSHOT'

jobs:
  trigger-release:
    runs-on: ubuntu-20.04
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          clean verify
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Set release version
        run: ./mvnw $MAVEN_CLI_OPTS versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
      - name: Commit release version
        run: git add ./\*pom.xml && git commit -m "New Release Version ${{ github.event.inputs.releaseVersion }}"
      - name: Add release tag
        run: git tag -a -m "v${{ github.event.inputs.releaseVersion }}" v${{ github.event.inputs.releaseVersion }}
      - name: Push release version
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Set new snapshot version
        run: ./mvnw $MAVEN_CLI_OPTS versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
      - name: Commit new snapshot version
        run: git add ./\*pom.xml && git commit -m "Prepare Next Snapshot Version ${{ github.event.inputs.nextVersion }}"
      - name: Push snapshot commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
